name: Rioja NET Live Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  riojanet_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./eShopWeb.sln
    - name: Build
      run: dotnet build ./eShopWeb.sln --no-restore
    - name: Test
      run: dotnet test ./eShopWeb.sln --no-build --verbosity normal
