name: (NO DOCKER)CI/CD .Net Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      build_config: release
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.402  
    - name: Restore dependencies
      run: dotnet restore ./eShopOnWeb.sln
    - name: Build
      run: dotnet build ./eShopOnWeb.sln --no-restore -c $build_config
    - name: Test
      run: dotnet test ./eShopOnWeb.sln --no-build --verbosity normal -c $build_config
    - name: Publish
      working-directory: ./src/Web
      run: dotnet publish --no-restore -o ../../web_publish -c $build_config
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:      
        name: web
        path: ./web_publish
