name: (NO DOCKER)CI/CD .Net Core
# trigger demo again
on: 
  workflow_dispatch:
  push:
    branches: [ restore_simple_webapp_version ] 

jobs:
  build_nodocker:
    runs-on: ubuntu-latest
    env:
      build_config: Release
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402  
    - name: Install dotnet tools
      run: dotnet tool restore
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration $build_config
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration $build_config
    - name: Publish site
      working-directory: ./src/Web
      run: dotnet publish -c $build_config -o ../../web_publish
    - name: Catalog SQL Script
      run: dotnet ef migrations script -c catalogcontext -i -p ./src/Infrastructure/Infrastructure.csproj -s ./src/Web/Web.csproj -o ./scripts/catalog.sql
    - name: Identity SQL Script
      run: dotnet ef migrations script -c appidentitydbcontext  -i -p ./src/Infrastructure/Infrastructure.csproj -s ./src/Web/Web.csproj -o ./scripts/identity.sql
    - name: Upload scripts
      uses: actions/upload-artifact@v2
      with:
        name: sql_scripts
        path: ./scripts
    - name: Upload site
      uses: actions/upload-artifact@v2
      with:
        name: web_site
        path: ./web_publish
    - name: Upload ARM
      uses: actions/upload-artifact@v2
      with:
        name: arm_template
        path: arm
    - name: Upload Loadtests
      uses: actions/upload-artifact@v2
      with:
        name: load_tests
        path: load_tests
  deploy_nodocker:
    needs: build_nodocker
    environment: load_tests
    runs-on: windows-latest
    steps:
    - name: Download scripts
      uses: actions/download-artifact@v2
      with:
        name: sql_scripts
        path: sql_scripts
    - name: Download site
      uses: actions/download-artifact@v2
      with:
        name: web_site
        path: web_site
    - name: Download arm
      uses: actions/download-artifact@v2
      with:
        name: arm_template
        path: arm_template
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1
      with:        
        scope: resourcegroup
        subscriptionId: '26da47a8-c28d-4564-ae8e-8ba88e995a0a'     
        resourceGroupName: 'NetCore_NoDocker_GIthubCI_CD_RG'
        # Specify the path or URL to the Azure Resource Manager template.
        template: arm_template/netcore_no_docker_rg_arm.json
        deploymentMode: Incremental
        deploymentName: deploy-${{ github.run_id }}
        parameters: sites_netcoregithub_name=netcoregithubapp sqlserver_password=${{ secrets.DB_PASSWORD }}

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: netcoregithubapp      
        package: web_site
        slot-name: swap

    - name: Azure App Service Settings
      uses: Azure/appservice-settings@v1
      with:
        app-name: netcoregithubapp
        connection-strings-json: ${{ secrets.CONNSTRING_JSON }}
        slot-name: swap 

    - name: Azure SQL Deploy
      uses: Azure/sql-action@v1
      with:
        server-name: netcoregithub.database.windows.net
        connection-string: ${{ secrets.CATALOG_DB_CONNSTRING }}
        sql-file: sql_scripts/catalog.sql
        
    - name: Azure SQL Deploy
      uses: Azure/sql-action@v1
      with:
        server-name: netcoregithub.database.windows.net
        connection-string: ${{ secrets.IDENTITY_DB_CONNSTRING }}
        sql-file: sql_scripts/identity.sql
        
  swap-slots:
    needs: deploy_nodocker
    environment: load_tests
    runs-on: ubuntu-latest
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:        
          inlineScript: az webapp deployment slot swap --slot -g NetCore_NoDocker_GIthubCI_CD_RG -n netcoregithubapp --slot swap --target-slot production      

    # - name: Download load_tests
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: load_tests
    #     path: load_tests
        
    # - name: Azure Load Testing
    #   uses: Azure/load-testing@v1
    #   with:
    #     # Path of the YAML file. Should be fully qualified path or relative to the default working directory
    #     loadtestConfigFile: load_tests/eshop.loadtests.yml
    #     # Enter or Select the name of an existing Azure Load Testing resource
    #     loadtestResource: lfloadtestsdemo
    #     # Enter or Select the Azure Resource Group that contains the Load test resource specified above
    #     resourceGroup: LoadTestingRG
